### ISSUE TITLE
"Download" button on project home page leads to 404

### ISSUE THREAD

**Issue by shaggyfrog** [eclipse-ee4j/jersey#4487] opened 2020-05-24 03:17 UTC
The "Download" button in the upper-right corner of the home page at https://eclipse-ee4j.github.io/jersey/ leads to a 404 on GitHub Pages.

**Comment by senivam** [comment] 2020-06-29 07:36
the issue is related to the main template, there is a PR which shall fix that: 

https://github.com/EclipseFdn/jekyll-theme-eclipsefdn/pull/2

**Comment by jansupol** [comment] 2020-09-21 20:50
The PR is merged, but the Download button still is not working. Interestingly, https://eclipse-ee4j.github.io/yasson works

**Comment by senivam** [comment] 2020-11-23 12:18
fixed

**Closed by senivam** 2020-11-23 12:18 UTC
