### ISSUE TITLE
Certain @Path configuration fail to resolve resource method (404 Not Found)

### ISSUE THREAD

**Issue by stanio** [eclipse-ee4j/jersey#4557] opened 2020-08-31 12:04 UTC
I've initially filled this in the Eclipse Bugzilla [#566521](https://bugs.eclipse.org/bugs/show_bug.cgi?id=566521).

Using `@Path` configuration as following:

```java
@Path("/rest")
public class FooResource {

    @GET
    @Path("/foo")
    @Produces(MediaType.TEXT_PLAIN)
    public String foo() {
        return "foo";
    }

}

@Path("/rest/foo")
public class BarResource {

    @GET
    @Path("/bar")
    @Produces(MediaType.TEXT_PLAIN)
    public String bar() {
        return "bar";
    }

    @GET
    @Path("/baz")
    @Produces(MediaType.TEXT_PLAIN)
    public String baz() {
        return "baz";
    }

}
```

causes `GET /rest/foo` to return 404 Not Found, while `GET /rest/foo/bar` and `GET /rest/foo/baz` return 200 OK as expected.  FWIW, I'm seeing `GET /application.wadl`:

```xml
    <resources base="http://localhost:8080/server-paths/">
        <resource path="/rest/foo">
            <resource path="/bar">
                <method id="bar" name="GET">...</method>
            </resource>
            <resource path="/baz">
                <method id="baz" name="GET">...</method>
            </resource>
        </resource>
        <resource path="/rest">
            <resource path="/foo">
                <method id="foo" name="GET">...</method>
            </resource>
        </resource>
    </resources>
```

which doesn't suggest any wrongdoing to me.  Changing the `@Path` declarations as following:

```java
@Path("/rest")
public class BarResource {

    @GET
    @Path("/foo/bar")
    @Produces(MediaType.TEXT_PLAIN)
    public String bar() {
        return "bar";
    }

    @GET
    @Path("/foo/baz")
    @Produces(MediaType.TEXT_PLAIN)
    public String baz() {
        return "baz";
    }

}
```

appears to work around the problem.  Try out [server-paths.zip](https://github.com/eclipse-ee4j/jersey/files/5150135/server-paths.zip) – a minimal WAR project demonstrating the problem.

**Comment by stanio** [comment] 2020-08-31 12:12
FWIW, I'm trying this deploying into a default Tomcat 8.5 distribution.

**Comment by stanio** [comment] 2020-08-31 17:56
I'm currently looking at the [_JAX-RS specification – § 3.7.2 Request Matching_](https://download.oracle.com/otn-pub/jcp/jaxrs-2_1-final-eval-spec/jaxrs-2_1-final-spec.pdf) to find out if it is a spec deficiency or implementation bug but I think from a user perspective the original case should work just fine – there's no ambiguity which request should match which resource method.

**Comment by stanio** [comment] 2020-08-31 18:44
> I'm currently looking at the _JAX-RS specification – § 3.7.2 Request Matching_...

O.k.  It seems to be a problem in the spec:

> 1.  Identify a set of candidate root resource classes matching the request:

The result of this would be an ordererd set:

```
/rest/foo() 	BarResource
/rest(/foo) 	FooResource
```

I think the following section is problematic:

> 2.  Obtain a set of candidate resource methods for the request:
> 
> **Input** _U_ = final capturing group not yet matched, _C′_ = {root resouce classes matched so far}
> **Output** _M_ = {candidate resource methods}
> 
> (a)  If _U_ is null or ‘/’...
> ...
> (b)  Set _E_ = {}.
> (c)  For each class _Z′_ in _C′_ add regular expressions to _E_ for each sub-resource method and locator...
> (d)  Filter _E_ by matching each member against _U_...

The _U_ used to match against could not/should not be the same for all classes but the spec is written as such it is likely behaving like that.  This explains why the second form behaves as expected:

```java
@Path("/rest")
public class FooResource {
...

@Path("/rest")
public class BarResource {
```

I think the JAX-RS spec could be improved in this part, or implementations should be able to warn for such setups.  The latter seems much more complex to detect and implement, and I think the original case should really just work – so I would love to see the JAX-RS revisited here.

**Comment by senivam** [comment] 2020-09-01 05:30
Hello @stanio, 

Regarding your last comment, you can put it for discussion directly to [JAXRS-API issue tracker](https://github.com/eclipse-ee4j/jaxrs-api/issues). 

And regarding tracking of issues, this place is more frequently viewed than Eclipse's bugzilla (for Jersey issues)

**Comment by stanio** [comment] 2020-09-01 06:38
Thanks for the JAXRS-API tracker pointer, @senivam.  I'll put this issue for discussion there as I've tried RESTEasy is also behaving the same which kinda confirm it appears spec related.

**Comment by jansupol** [comment] 2020-09-02 11:27
I think we can close this, it works as designed by the Spec. Note that the issue is a corner-case, where one resource class has the same URI as a resource method from the other resource class.

**Closed by jansupol** 2020-09-02 11:27 UTC
