### ISSUE TITLE
3.1.4 broken release, JettyConnectorProvider always throws exception

### ISSUE THREAD

**Issue by rickardoberg** [eclipse-ee4j/jersey#5491] opened 2023-12-06 10:14 UTC
It seems like 3.1.4 is a broken release, as the JettyConnectorProvider always throws an exception:
```public class JettyConnectorProvider implements ConnectorProvider {

    @Override
    public Connector getConnector(Client client, Configuration runtimeConfig) {
        throw new ProcessingException(LocalizationMessages.NOT_SUPPORTED());
    }
}
```
I'm going to take a wild guess and say that you probably meant to include a non-exception-throwing version under META-INF/versions/17, but there is no such class. So, the connector simply doesn't work at the moment.

**Comment by senivam** [comment] 2023-12-06 10:50
yes, you are right.  Fix is being prepared. Meanwhile, you can use `jersey-jetty11-connector` [module added since 3.1.4 version] which works. The `jersey-jetty-connector` module which will be fixed in the next release is Jetty 12 based. While `jersey-jetty11-connector` keeps backwards compatibility for the Jetty 11

**Comment by senivam** [comment] 2023-12-12 14:20
the 3.1.5 is out. The issue is fixed.

**Closed as completed by senivam** 2023-12-12 14:20 UTC
