### ISSUE TITLE
jersey-media-json-processing - 3.0.0-M1 is missing

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jersey#4454] opened 2020-04-29 02:08 UTC
GF uses this but v 3.0.0-M1 is not available. Is that intentional and/or what is the replacement, if there is any?

**Comment by lukasj** [comment] 2020-04-29 02:23
same issue with jersey-media-moxy

**Comment by jansupol** [comment] 2020-05-11 10:34
jersey-media-json-processing is excluded from M1, since at the time of the creation there was no jsonp-jaxrs jar we depend on that would have been using JAX-RS 3.0.0-RC1 API.

The same is with jersey-media-moxy, MOXyJsonProvider at the time of M1 was still using JAX-RS 2.x API.

**Comment by jansupol** [comment] 2020-05-11 10:41
@lukasj [JSON-P RC2](https://mvnrepository.com/artifact/org.glassfish/jsonp-jaxrs/2.0.0-RC2 ) is still using the old JAX-RS API.

**Comment by lukasj** [comment] 2020-05-11 10:44
@jansupol why don't you file a bug there?

**Comment by jansupol** [comment] 2020-05-20 07:12
jersey-media-json-processing is to be missing forever. Closing as "works as designed".

**Comment by lukasj** [comment] 2020-05-20 11:19
does the same apply to `jersey-media-moxy` as well?

**Comment by jansupol** [comment] 2020-05-22 21:35
They are not in M2 either. Should be in M3, hopefully.

**Comment by senivam** [comment] 2020-05-29 07:08
jersey-media-moxy is back in the M3 version (which is currently in staging). Regarding what is going to be missing forever, is jersey-media-json-jackson1 which was removed from the 3d (3.0.0*) version.

**Closed by senivam** 2020-05-29 07:08 UTC
